# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/SUZ-tsinghua"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://twitter.com"

[social.params]
icon = "brand-twitter"

[[social]]
identifier = "google scholar"
name = "Google scholar"
url = "https://scholar.google.com/citations?user=R5Y1xlUAAAAJ&hl=zh-CN&oi=sra"

[social.params]
icon = "brand-google"
